language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-mobius' ]; then cd .. && eval "mv $currentfolder generator-mobius" && cd generator-mobius; fi

